// Mocks generated by Mockito 5.1.0 from annotations
// in beauty_of_space/test/api_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:beauty_of_space/data/repositories/apod_repository.dart' as _i3;
import 'package:beauty_of_space/domain/models/apod/picture.dart' as _i5;
import 'package:beauty_of_space/domain/services/nasa_service/nasa_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeNasaService_0 extends _i1.Fake implements _i2.NasaService {}

/// A class which mocks [ApodRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockApodRepository extends _i1.Mock implements _i3.ApodRepository {
  MockApodRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NasaService get service =>
      (super.noSuchMethod(Invocation.getter(#service),
          returnValue: _FakeNasaService_0()) as _i2.NasaService);
  @override
  _i4.Future<List<_i5.Picture>> getApod({String? startDate, String? endDate}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getApod, [], {#startDate: startDate, #endDate: endDate}),
              returnValue: Future<List<_i5.Picture>>.value(<_i5.Picture>[]))
          as _i4.Future<List<_i5.Picture>>);
}
